# Generated by Django 3.0.4 on 2020-03-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0002_auto_20200324_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rai', models.IntegerField(verbose_name='rai')),
                ('date', models.DateField(verbose_name='Data da Escala')),
                ('horas_trabalhada', models.CharField(max_length=3, verbose_name='Horas')),
                ('servico', models.CharField(choices=[('extraordinario', 'Extraordinário'), ('odrinario', 'Ordinário')], max_length=20, verbose_name='Servico')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Pessoa')),
            ],
            options={
                'verbose_name': 'rai',
                'verbose_name_plural': 'rais',
            },
        ),
    ]
