# Generated by Django 3.0.4 on 2020-04-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0003_auto_20200329_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viatura', models.CharField(max_length=20, verbose_name='viatura')),
                ('tipo', models.CharField(choices=[('oficial', 'Oficial'), ('reserva', 'Reserva')], max_length=20, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'viatura',
                'verbose_name_plural': 'viatura',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rai', models.IntegerField(verbose_name='rai')),
                ('date', models.DateField(verbose_name='Data da Escala')),
                ('horas_trabalhada', models.CharField(max_length=3, verbose_name='Horas')),
                ('servico', models.CharField(choices=[('extraordinario', 'Extraordinário'), ('odrinario', 'Ordinário')], max_length=20, verbose_name='Servico')),
                ('quilometragem', models.IntegerField(verbose_name='KM')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analistas', to='pessoa.Pessoa')),
                ('comandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandantes', to='pessoa.Pessoa')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motoristas', to='pessoa.Pessoa')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.Viatura')),
            ],
            options={
                'verbose_name': 'rai',
                'verbose_name_plural': 'rais',
            },
        ),
    ]
