# Generated by Django 3.0.4 on 2020-03-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viatura', models.CharField(max_length=20, verbose_name='viatura')),
                ('tipo', models.CharField(choices=[('oficial', 'Oficial'), ('reserva', 'Reserva')], max_length=20, verbose_name='tipo')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='escala.Viatura'),
            preserve_default=False,
        ),
    ]
