# Generated by Django 3.0.4 on 2020-03-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_auto_20200325_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viatura',
            options={'verbose_name': 'viatura', 'verbose_name_plural': 'viatura'},
        ),
    ]
