# Generated by Django 3.0.4 on 2020-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_auto_20200325_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='quilometragem',
            field=models.IntegerField(default=1, verbose_name='KM'),
            preserve_default=False,
        ),
    ]
