# Generated by Django 3.0.4 on 2020-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('graduacao', models.CharField(max_length=50, verbose_name='graduacao')),
                ('rg_funcional', models.CharField(max_length=7, unique=True)),
                ('cpf', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'graduacao',
                'verbose_name_plural': 'graduacoes',
                'ordering': ('graduacao',),
            },
        ),
    ]
