# Generated by Django 3.0.4 on 2020-03-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ('nome',), 'verbose_name': 'nome', 'verbose_name_plural': 'nomes'},
        ),
    ]
